groups:
  - name: prometheus
    rules:
      - alert: PrometheusBadConfig
        annotations:
          description:
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to
            reload its configuration.
          summary: Failed Prometheus configuration reload.
        expr: |-
          # Without max_over_time, failed scrapes could create false negatives, see
          # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.
          max_over_time(prometheus_config_last_reload_successful[5m]) == 0
        for: 10m
        labels:
          severity: critical

      - alert: PrometheusErrorSendingAlertsToAnyAlertmanager
        annotations:
          description:
            '{{ printf "%.1f" $value }}% minimum errors while sending alerts
            from Prometheus {{$labels.namespace}}/{{$labels.pod}} to any Alertmanager.'
          summary: Prometheus encounters more than 3% errors sending alerts to any Alertmanager.
        expr: |-
          min without(alertmanager) (
            rate(prometheus_notifications_errors_total[5m])
          /
            rate(prometheus_notifications_sent_total[5m])
          )
          * 100
          > 3
        for: 15m
        labels:
          severity: critical

      - alert: PrometheusNotConnectedToAlertmanagers
        annotations:
          description:
            Prometheus {{$labels.namespace}}/{{$labels.pod}} is not connected
            to any Alertmanagers.
          summary: Prometheus is not connected to any Alertmanagers.
        expr: |-
          # Without max_over_time, failed scrapes could create false negatives, see
          # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.
          max_over_time(prometheus_notifications_alertmanagers_discovered[5m]) < 1
        for: 10m
        labels:
          severity: warning

      - alert: PrometheusRemoteStorageFailures
        annotations:
          description:
            Prometheus {{$labels.namespace}}/{{$labels.pod}} failed to send
            {{ printf "%.1f" $value }}% of the samples to {{ $labels.remote_name}}:{{
            $labels.url }}
          summary: Prometheus fails to send samples to remote storage.
        expr: |-
          (
            rate(prometheus_remote_storage_failed_samples_total[5m])
          /
            (
              rate(prometheus_remote_storage_failed_samples_total[5m])
            +
              rate(prometheus_remote_storage_succeeded_samples_total[5m])
            )
          )
          * 100
          > 1
        for: 15m
        labels:
          severity: critical

      - alert: PrometheusRemoteWriteBehind
        annotations:
          description:
            Prometheus {{$labels.namespace}}/{{$labels.pod}} remote write is
            {{ printf "%.1f" $value }}s behind for {{ $labels.remote_name}}:{{ $labels.url
            }}.
          summary: Prometheus remote write is behind.
        expr: |-
          # Without max_over_time, failed scrapes could create false negatives, see
          # https://www.robustperception.io/alerting-on-gauges-in-prometheus-2-0 for details.
          (
            max_over_time(prometheus_remote_storage_highest_timestamp_in_seconds[5m])
          - on(job, instance) group_right
            max_over_time(prometheus_remote_storage_queue_highest_sent_timestamp_seconds[5m])
          )
          > 120
        for: 15m
        labels:
          severity: critical

      - alert: PrometheusRuleFailures
        annotations:
          description:
            Prometheus {{$labels.namespace}}/{{$labels.pod}} has failed to
            evaluate {{ printf "%.0f" $value }} rules in the last 5m.
          summary: Prometheus is failing rule evaluations.
        expr: |-
          increase(prometheus_rule_evaluation_failures_total[5m])
          > 0
        for: 15m
        labels:
          severity: critical
